# Generated by Django 3.1.7 on 2023-07-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
