# Generated by Django 3.1.7 on 2023-07-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230725_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='review',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
