# Generated by Django 3.1.7 on 2023-07-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20230725_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='review',
            field=models.TextField(default='{}'),
        ),
    ]
